#!/usr/bin/env bash
export HUSKY_TOP_PLATE_ENABLED=true
export HUSKY_USER_RAIL_ENABLED=true

export HUSKY_URDF_EXTRAS=$(catkin_find husky_ur_description urdf/husky_dual_ur5_e_description.urdf.xacro --first-only)
